name: Build Sit Straight (Simple)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build the app (arm64 only)
      run: |
        xcodebuild -project SitStraight.xcodeproj -scheme SitStraight -configuration Release -destination "platform=macOS,arch=arm64" build -derivedDataPath ./DerivedData

    - name: Create app bundle
      run: |
        mkdir -p dist
        cp -R DerivedData/Build/Products/Release/SitStraight.app dist/

        # Verify the binary
        echo "Binary info:"
        file dist/SitStraight.app/Contents/MacOS/SitStraight
        lipo -info dist/SitStraight.app/Contents/MacOS/SitStraight

    - name: Upload built app
      uses: actions/upload-artifact@v4
      with:
        name: SitStraight.app
        path: dist/SitStraight.app
        retention-days: 30
